version: '3'

volumes:
  {{cookiecutter.app_name}}-data:
    driver: local

services:
  app:
  environment:
    - APP_SETTINGS={{cookiecutter.app_name}}.settings.DevConfig
  volumes:
    - ./app:/app
