blank_issues_enabled: false
contact_links:
  - name: Report a Security vulnerability
    url: https://github.com/cookiecutter-flask/cookiecutter-flask/security/policy
    about: Please report security vulnerabilities here.
